# Generated by Django 5.2.3 on 2025-07-05 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.CharField(choices=[('50_24', '50% in 24 hours')], max_length=10)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('investment', 'Investment'), ('withdrawal', 'Withdrawal')], default='investment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('merged', 'Merged'), ('awaiting', 'Awaiting'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('sender_confirmed', models.BooleanField(default=False)),
                ('receiver_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_recommit', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('admin_paid', models.BooleanField(default=False, null=True)),
                ('merged_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_bids', to='bids.bid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
