# Generated by Django 5.2.3 on 2025-06-25 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.CharField(choices=[('50_24', '50% in 24 hours')], max_length=10)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('sender_confirmed', models.BooleanField(default=False)),
                ('receiver_confirmed', models.BooleanField(default=False)),
                ('in_auction_room', models.BooleanField(default=False)),
                ('receiver_account', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('merged_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_bids', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
