# Generated by Django 5.2.3 on 2025-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='in_auction_room',
            field=models.BooleanField(default=False),
        ),
    ]
