# Generated by Django 5.2.3 on 2025-06-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bid_in_auction_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='receiver_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='receiver_bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
