# Generated by Django 5.2.3 on 2025-06-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_remove_bid_in_auction_room_bid_can_recommit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='type',
            field=models.CharField(choices=[('investment', 'Investment'), ('withdrawal', 'Withdrawal')], default='investment', max_length=20),
        ),
    ]
