# Generated by Django 5.2.3 on 2025-07-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_remove_bid_merged_with_remove_bid_receiver_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='merged_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_bids', to='bids.bid'),
        ),
    ]
