# Generated by Django 5.2.3 on 2025-07-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_alter_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='admin_paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('merged', 'Merged'), ('awaiting', 'Awaiting'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
