# Generated by Django 5.2.3 on 2025-06-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_auction_room',
            field=models.BooleanField(default=False),
        ),
    ]
