# Generated by Django 5.2.3 on 2025-06-23 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MergeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_time', models.TimeField(default=datetime.time(8, 0))),
                ('evening_time', models.TimeField(default=datetime.time(18, 30))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
