# Generated by Django 5.2.3 on 2025-07-05 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergesettings',
            name='afternoon_time',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AddField(
            model_name='mergesettings',
            name='auction_duration_minutes',
            field=models.IntegerField(default=3),
        ),
    ]
