# Generated by Django 5.2.3 on 2025-07-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_mergesettings_afternoon_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergesettings',
            name='afternoon_time',
        ),
    ]
